name: campo_minado
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stop_watch_timer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/1024.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/icons/1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/aberto_0.jpeg
    - assets/images/aberto_1.jpeg
    - assets/images/aberto_2.jpeg
    - assets/images/aberto_3.jpeg
    - assets/images/aberto_4.jpeg
    - assets/images/aberto_5.jpeg
    - assets/images/aberto_6.jpeg
    - assets/images/aberto_7.jpeg
    - assets/images/aberto_8.jpeg
    - assets/images/bandeira.jpeg
    - assets/images/bomba_0.jpeg
    - assets/images/bomba_1.jpeg
    - assets/images/fechado.jpeg
